In [1]:
import numpy as np

In [2]:
Y = [
    [      1,       1,       1,     10],
    [      2,       2,       2,     20],
    [      3,       1,       1,     10],
    [      4,       2,       2,     20],
    [      5,       1,       1,    100],
    [      6,       2,       2,    100],
    [      7,       1,       1,     10],
    [      8,       2,       2,     20]
    ]

In [3]:
X = [
    [      1,       1,       1,     10],
    [      2,       2,       2,     20],
    [      3,       1,       1,     10],
    [      4,       2,       2,     20],
    [      5,       1,       1, np.nan],
    [      6,       2,       2, np.nan],
    [      7,       1,       1,     10],
    [      8,       2,       2,     20]
    ]

In [4]:
from missingpy import KNNImputer

imputer = KNNImputer(n_neighbors=3, weights="uniform")
imputer.fit_transform(X)

array([[ 1.        ,  1.        ,  1.        , 10.        ],
       [ 2.        ,  2.        ,  2.        , 20.        ],
       [ 3.        ,  1.        ,  1.        , 10.        ],
       [ 4.        ,  2.        ,  2.        , 20.        ],
       [ 5.        ,  1.        ,  1.        , 13.33333333],
       [ 6.        ,  2.        ,  2.        , 16.66666667],
       [ 7.        ,  1.        ,  1.        , 10.        ],
       [ 8.        ,  2.        ,  2.        , 20.        ]])

In [5]:
from missingpy import MissForest

imputer = MissForest(random_state=1337)
imputer.fit_transform(X)

Iteration: 0
Iteration: 1
Iteration: 2


array([[ 1. ,  1. ,  1. , 10. ],
       [ 2. ,  2. ,  2. , 20. ],
       [ 3. ,  1. ,  1. , 10. ],
       [ 4. ,  2. ,  2. , 20. ],
       [ 5. ,  1. ,  1. , 10.6],
       [ 6. ,  2. ,  2. , 19.7],
       [ 7. ,  1. ,  1. , 10. ],
       [ 8. ,  2. ,  2. , 20. ]])

In [6]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit_transform(X)

array([[ 1.,  1.,  1., 10.],
       [ 2.,  2.,  2., 20.],
       [ 3.,  1.,  1., 10.],
       [ 4.,  2.,  2., 20.],
       [ 5.,  1.,  1., 15.],
       [ 6.,  2.,  2., 15.],
       [ 7.,  1.,  1., 10.],
       [ 8.,  2.,  2., 20.]])